#!/bin/bash

# /boot/firmware
if [ -d /boot/firmware ]; then
  $(mount -o remount,rw / >/dev/null 2>&1 </dev/null ; mount -o remount,rw /boot/firmware >/dev/null 2>&1 </dev/null)
else
  $(mount -o remount,rw / >/dev/null 2>&1 </dev/null ; mount -o remount,rw /boot >/dev/null 2>&1 </dev/null)
fi

/usr/bin/apt-get "$@"
